spring:
  application:
    name: flowpay-routing

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flowpay}
    username: ${DB_USERNAME:flowpay_user}
    password: ${DB_PASSWORD:flowpay_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flowpay}
    user: ${DB_USERNAME:flowpay_user}
    password: ${DB_PASSWORD:flowpay_pass}
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080
