spring:
  application:
    name: flowpay-routing

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/flowpay}
    username: ${DATABASE_USERNAME:${DB_USERNAME:flowpay_user}}
    password: ${DATABASE_PASS:${DB_PASSWORD:flowpay_pass}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/flowpay}
    user: ${DATABASE_USERNAME:${DB_USERNAME:flowpay_user}}
    password: ${DATABASE_PASS:${DB_PASSWORD:flowpay_pass}}
    baseline-on-migrate: true

  data:
    redis:
      url: ${REDIS_URL:}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_TOKEN:${REDIS_PASSWORD:}}

server:
  port: 8080
